name: Code Quality

on:
  pull_request:
    branches: "main"
  push:
    branches: "main"

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"

    - name: Format check with black
      run: |
        black --check --diff src/logsmith tests/

    - name: Sort imports check with isort
      run: |
        isort --check-only --diff src/logsmith tests/

    - name: Lint with flake8
      run: |
        flake8 src/logsmith tests/ --max-line-length=88 --extend-ignore=E203,W503

    - name: Type check with mypy
      run: |
        mypy src/logsmith --ignore-missing-imports

  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install bandit
      run: |
        python -m pip install --upgrade pip
        pip install bandit[toml]

    - name: Run security checks with bandit
      run: |
        bandit -r src/logsmith -f json || true
